In [1]:
import pandas as pd
dataset = pd.read_csv("insurance_pre.csv")

In [2]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset = pd.get_dummies(dataset, drop_first = True).astype(int)

In [4]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
independent = dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [7]:
dependent = dataset[['charges']]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(independent, dependent, test_size=1/3, random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR

param_grid = {'kernel': ['rbf', 'poly', 'linear'], 'C': [0.1, 1, 10, 100, 1000],
    'epsilon': [0.001, 0.01, 0.1, 0.5, 1],
    'gamma': ['scale', 'auto']}

grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3, n_jobs=1)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 150 candidates, totalling 750 fits
[CV 1/5] END C=0.1, epsilon=0.001, gamma=scale, kernel=rbf;, score=-0.054 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.001, gamma=scale, kernel=rbf;, score=-0.023 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.001, gamma=scale, kernel=rbf;, score=-0.160 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.001, gamma=scale, kernel=rbf;, score=-0.123 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.001, gamma=scale, kernel=rbf;, score=-0.141 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.001, gamma=scale, kernel=poly;, score=-0.053 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=0.1, epsilon=0.001, gamma=scale, kernel=poly;, score=-0.023 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.001, gamma=scale, kernel=poly;, score=-0.159 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.001, gamma=scale, kernel=poly;, score=-0.122 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.001, gamma=scale, kernel=poly;, score=-0.140 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.001, gamma=scale, kernel=linear;, score=-0.048 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.001, gamma=scale, kernel=linear;, score=-0.017 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.001, gamma=scale, kernel=linear;, score=-0.155 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.001, gamma=scale, kernel=linear;, score=-0.117 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.001, gamma=scale, kernel=linear;, score=-0.135 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.001, gamma=auto, kernel=rbf;, score=-0.054 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.001, gamma=auto, kernel=rbf;, score=-0.023 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 3/5] END C=0.1, epsilon=0.001, gamma=auto, kernel=rbf;, score=-0.160 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.001, gamma=auto, kernel=rbf;, score=-0.123 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.001, gamma=auto, kernel=rbf;, score=-0.141 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.001, gamma=auto, kernel=poly;, score=-0.053 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.001, gamma=auto, kernel=poly;, score=-0.023 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.001, gamma=auto, kernel=poly;, score=-0.159 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.001, gamma=auto, kernel=poly;, score=-0.122 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.001, gamma=auto, kernel=poly;, score=-0.140 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.001, gamma=auto, kernel=linear;, score=-0.048 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.001, gamma=auto, kernel=linear;, score=-0.017 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.001, gamma=auto, kernel=linear;, score=-0.155 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.001, gamma=auto, kernel=linear;, score=-0.117 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.001, gamma=auto, kernel=linear;, score=-0.135 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=rbf;, score=-0.054 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=rbf;, score=-0.023 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=rbf;, score=-0.160 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=rbf;, score=-0.123 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 5/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=rbf;, score=-0.141 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=poly;, score=-0.053 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=poly;, score=-0.023 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=poly;, score=-0.159 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=poly;, score=-0.122 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=poly;, score=-0.140 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=linear;, score=-0.048 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=linear;, score=-0.017 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=linear;, score=-0.155 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=linear;, score=-0.117 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.01, gamma=scale, kernel=linear;, score=-0.135 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=rbf;, score=-0.054 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=rbf;, score=-0.023 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=rbf;, score=-0.160 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=rbf;, score=-0.123 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=rbf;, score=-0.141 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=poly;, score=-0.053 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=poly;, score=-0.023 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=poly;, score=-0.159 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=poly;, score=-0.122 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=poly;, score=-0.140 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=linear;, score=-0.048 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=linear;, score=-0.017 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 3/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=linear;, score=-0.155 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=linear;, score=-0.117 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.01, gamma=auto, kernel=linear;, score=-0.135 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=rbf;, score=-0.054 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=rbf;, score=-0.023 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=rbf;, score=-0.160 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=rbf;, score=-0.123 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=rbf;, score=-0.141 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=poly;, score=-0.053 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=poly;, score=-0.023 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=poly;, score=-0.159 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=poly;, score=-0.122 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=poly;, score=-0.140 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=linear;, score=-0.048 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=linear;, score=-0.017 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=linear;, score=-0.155 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=linear;, score=-0.117 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.1, gamma=scale, kernel=linear;, score=-0.135 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=rbf;, score=-0.054 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=rbf;, score=-0.023 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=rbf;, score=-0.160 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=rbf;, score=-0.123 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=rbf;, score=-0.141 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=poly;, score=-0.053 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=poly;, score=-0.023 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=poly;, score=-0.159 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=poly;, score=-0.122 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=poly;, score=-0.140 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=linear;, score=-0.048 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=linear;, score=-0.017 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=linear;, score=-0.155 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=linear;, score=-0.117 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.1, gamma=auto, kernel=linear;, score=-0.135 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=rbf;, score=-0.054 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=rbf;, score=-0.023 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=rbf;, score=-0.160 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=rbf;, score=-0.123 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=rbf;, score=-0.141 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 1/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=poly;, score=-0.053 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=poly;, score=-0.023 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=poly;, score=-0.159 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=poly;, score=-0.122 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=poly;, score=-0.140 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=linear;, score=-0.048 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=linear;, score=-0.017 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=linear;, score=-0.155 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=linear;, score=-0.117 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.5, gamma=scale, kernel=linear;, score=-0.135 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=rbf;, score=-0.054 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=rbf;, score=-0.023 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=rbf;, score=-0.160 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=rbf;, score=-0.123 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=rbf;, score=-0.141 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=poly;, score=-0.053 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=poly;, score=-0.023 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 3/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=poly;, score=-0.159 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=poly;, score=-0.122 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=poly;, score=-0.140 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=linear;, score=-0.048 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=linear;, score=-0.017 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=linear;, score=-0.155 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=linear;, score=-0.117 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=0.5, gamma=auto, kernel=linear;, score=-0.135 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=1, gamma=scale, kernel=rbf;, score=-0.054 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=1, gamma=scale, kernel=rbf;, score=-0.023 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 3/5] END C=0.1, epsilon=1, gamma=scale, kernel=rbf;, score=-0.160 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=1, gamma=scale, kernel=rbf;, score=-0.123 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=1, gamma=scale, kernel=rbf;, score=-0.141 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=1, gamma=scale, kernel=poly;, score=-0.053 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=1, gamma=scale, kernel=poly;, score=-0.023 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=1, gamma=scale, kernel=poly;, score=-0.159 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=1, gamma=scale, kernel=poly;, score=-0.122 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=1, gamma=scale, kernel=poly;, score=-0.140 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=1, gamma=scale, kernel=linear;, score=-0.048 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=1, gamma=scale, kernel=linear;, score=-0.017 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 3/5] END C=0.1, epsilon=1, gamma=scale, kernel=linear;, score=-0.155 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=1, gamma=scale, kernel=linear;, score=-0.117 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=1, gamma=scale, kernel=linear;, score=-0.135 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=1, gamma=auto, kernel=rbf;, score=-0.054 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=1, gamma=auto, kernel=rbf;, score=-0.023 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=1, gamma=auto, kernel=rbf;, score=-0.160 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=1, gamma=auto, kernel=rbf;, score=-0.123 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=1, gamma=auto, kernel=rbf;, score=-0.141 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 1/5] END C=0.1, epsilon=1, gamma=auto, kernel=poly;, score=-0.053 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=1, gamma=auto, kernel=poly;, score=-0.023 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=1, gamma=auto, kernel=poly;, score=-0.159 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=1, gamma=auto, kernel=poly;, score=-0.122 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=1, gamma=auto, kernel=poly;, score=-0.140 total time=   0.0s
[CV 1/5] END C=0.1, epsilon=1, gamma=auto, kernel=linear;, score=-0.048 total time=   0.0s
[CV 2/5] END C=0.1, epsilon=1, gamma=auto, kernel=linear;, score=-0.017 total time=   0.0s
[CV 3/5] END C=0.1, epsilon=1, gamma=auto, kernel=linear;, score=-0.155 total time=   0.0s
[CV 4/5] END C=0.1, epsilon=1, gamma=auto, kernel=linear;, score=-0.117 total time=   0.0s
[CV 5/5] END C=0.1, epsilon=1, gamma=auto, kernel=linear;, score=-0.135 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.001, gamma=scale, kernel=rbf;, score=-0.049 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=1, epsilon=0.001, gamma=scale, kernel=rbf;, score=-0.019 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.001, gamma=scale, kernel=rbf;, score=-0.157 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.001, gamma=scale, kernel=rbf;, score=-0.119 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.001, gamma=scale, kernel=rbf;, score=-0.137 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.001, gamma=scale, kernel=poly;, score=-0.044 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.001, gamma=scale, kernel=poly;, score=-0.013 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.001, gamma=scale, kernel=poly;, score=-0.150 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.001, gamma=scale, kernel=poly;, score=-0.112 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.001, gamma=scale, kernel=poly;, score=-0.131 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.001, gamma=scale, kernel=linear;, score=0.008 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=1, epsilon=0.001, gamma=scale, kernel=linear;, score=0.042 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.001, gamma=scale, kernel=linear;, score=-0.100 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.001, gamma=scale, kernel=linear;, score=-0.063 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.001, gamma=scale, kernel=linear;, score=-0.085 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.001, gamma=auto, kernel=rbf;, score=-0.049 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.001, gamma=auto, kernel=rbf;, score=-0.019 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.001, gamma=auto, kernel=rbf;, score=-0.157 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.001, gamma=auto, kernel=rbf;, score=-0.119 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 5/5] END C=1, epsilon=0.001, gamma=auto, kernel=rbf;, score=-0.137 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.001, gamma=auto, kernel=poly;, score=-0.044 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.001, gamma=auto, kernel=poly;, score=-0.013 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.001, gamma=auto, kernel=poly;, score=-0.150 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.001, gamma=auto, kernel=poly;, score=-0.112 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.001, gamma=auto, kernel=poly;, score=-0.132 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.001, gamma=auto, kernel=linear;, score=0.008 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.001, gamma=auto, kernel=linear;, score=0.042 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.001, gamma=auto, kernel=linear;, score=-0.100 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.001, gamma=auto, kernel=linear;, score=-0.063 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.001, gamma=auto, kernel=linear;, score=-0.085 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.01, gamma=scale, kernel=rbf;, score=-0.049 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=1, epsilon=0.01, gamma=scale, kernel=rbf;, score=-0.019 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.01, gamma=scale, kernel=rbf;, score=-0.157 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.01, gamma=scale, kernel=rbf;, score=-0.119 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.01, gamma=scale, kernel=rbf;, score=-0.137 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.01, gamma=scale, kernel=poly;, score=-0.044 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.01, gamma=scale, kernel=poly;, score=-0.013 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.01, gamma=scale, kernel=poly;, score=-0.150 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.01, gamma=scale, kernel=poly;, score=-0.112 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.01, gamma=scale, kernel=poly;, score=-0.131 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.01, gamma=scale, kernel=linear;, score=0.008 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=1, epsilon=0.01, gamma=scale, kernel=linear;, score=0.042 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.01, gamma=scale, kernel=linear;, score=-0.100 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.01, gamma=scale, kernel=linear;, score=-0.064 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.01, gamma=scale, kernel=linear;, score=-0.085 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.01, gamma=auto, kernel=rbf;, score=-0.049 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.01, gamma=auto, kernel=rbf;, score=-0.019 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.01, gamma=auto, kernel=rbf;, score=-0.157 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.01, gamma=auto, kernel=rbf;, score=-0.119 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 5/5] END C=1, epsilon=0.01, gamma=auto, kernel=rbf;, score=-0.137 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.01, gamma=auto, kernel=poly;, score=-0.044 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.01, gamma=auto, kernel=poly;, score=-0.013 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.01, gamma=auto, kernel=poly;, score=-0.150 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.01, gamma=auto, kernel=poly;, score=-0.112 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.01, gamma=auto, kernel=poly;, score=-0.132 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.01, gamma=auto, kernel=linear;, score=0.008 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.01, gamma=auto, kernel=linear;, score=0.042 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.01, gamma=auto, kernel=linear;, score=-0.100 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.01, gamma=auto, kernel=linear;, score=-0.064 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.01, gamma=auto, kernel=linear;, score=-0.085 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 1/5] END C=1, epsilon=0.1, gamma=scale, kernel=rbf;, score=-0.049 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.1, gamma=scale, kernel=rbf;, score=-0.019 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.1, gamma=scale, kernel=rbf;, score=-0.157 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.1, gamma=scale, kernel=rbf;, score=-0.119 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.1, gamma=scale, kernel=rbf;, score=-0.137 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.1, gamma=scale, kernel=poly;, score=-0.044 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.1, gamma=scale, kernel=poly;, score=-0.013 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.1, gamma=scale, kernel=poly;, score=-0.150 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.1, gamma=scale, kernel=poly;, score=-0.112 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 5/5] END C=1, epsilon=0.1, gamma=scale, kernel=poly;, score=-0.131 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.1, gamma=scale, kernel=linear;, score=0.008 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.1, gamma=scale, kernel=linear;, score=0.042 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.1, gamma=scale, kernel=linear;, score=-0.100 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.1, gamma=scale, kernel=linear;, score=-0.064 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.1, gamma=scale, kernel=linear;, score=-0.085 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.1, gamma=auto, kernel=rbf;, score=-0.049 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.1, gamma=auto, kernel=rbf;, score=-0.019 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.1, gamma=auto, kernel=rbf;, score=-0.157 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.1, gamma=auto, kernel=rbf;, score=-0.119 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 5/5] END C=1, epsilon=0.1, gamma=auto, kernel=rbf;, score=-0.137 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.1, gamma=auto, kernel=poly;, score=-0.044 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.1, gamma=auto, kernel=poly;, score=-0.013 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.1, gamma=auto, kernel=poly;, score=-0.150 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.1, gamma=auto, kernel=poly;, score=-0.112 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.1, gamma=auto, kernel=poly;, score=-0.132 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.1, gamma=auto, kernel=linear;, score=0.008 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.1, gamma=auto, kernel=linear;, score=0.042 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.1, gamma=auto, kernel=linear;, score=-0.100 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.1, gamma=auto, kernel=linear;, score=-0.064 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.1, gamma=auto, kernel=linear;, score=-0.085 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.5, gamma=scale, kernel=rbf;, score=-0.049 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=1, epsilon=0.5, gamma=scale, kernel=rbf;, score=-0.019 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.5, gamma=scale, kernel=rbf;, score=-0.157 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.5, gamma=scale, kernel=rbf;, score=-0.119 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.5, gamma=scale, kernel=rbf;, score=-0.137 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.5, gamma=scale, kernel=poly;, score=-0.044 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.5, gamma=scale, kernel=poly;, score=-0.013 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.5, gamma=scale, kernel=poly;, score=-0.150 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.5, gamma=scale, kernel=poly;, score=-0.112 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.5, gamma=scale, kernel=poly;, score=-0.131 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 1/5] END C=1, epsilon=0.5, gamma=scale, kernel=linear;, score=0.008 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.5, gamma=scale, kernel=linear;, score=0.042 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.5, gamma=scale, kernel=linear;, score=-0.100 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.5, gamma=scale, kernel=linear;, score=-0.064 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.5, gamma=scale, kernel=linear;, score=-0.085 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.5, gamma=auto, kernel=rbf;, score=-0.049 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.5, gamma=auto, kernel=rbf;, score=-0.019 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.5, gamma=auto, kernel=rbf;, score=-0.157 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.5, gamma=auto, kernel=rbf;, score=-0.119 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 5/5] END C=1, epsilon=0.5, gamma=auto, kernel=rbf;, score=-0.137 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.5, gamma=auto, kernel=poly;, score=-0.044 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.5, gamma=auto, kernel=poly;, score=-0.013 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.5, gamma=auto, kernel=poly;, score=-0.150 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.5, gamma=auto, kernel=poly;, score=-0.112 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.5, gamma=auto, kernel=poly;, score=-0.132 total time=   0.0s
[CV 1/5] END C=1, epsilon=0.5, gamma=auto, kernel=linear;, score=0.008 total time=   0.0s
[CV 2/5] END C=1, epsilon=0.5, gamma=auto, kernel=linear;, score=0.042 total time=   0.0s
[CV 3/5] END C=1, epsilon=0.5, gamma=auto, kernel=linear;, score=-0.100 total time=   0.0s
[CV 4/5] END C=1, epsilon=0.5, gamma=auto, kernel=linear;, score=-0.064 total time=   0.0s
[CV 5/5] END C=1, epsilon=0.5, gamma=auto, kernel=linear;, score=-0.085 total time=   0.0s
[CV 1/5] END C=1, epsilon=1, gamma=scale, kernel=rbf;, score=-0.049 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=1, epsilon=1, gamma=scale, kernel=rbf;, score=-0.019 total time=   0.0s
[CV 3/5] END C=1, epsilon=1, gamma=scale, kernel=rbf;, score=-0.157 total time=   0.0s
[CV 4/5] END C=1, epsilon=1, gamma=scale, kernel=rbf;, score=-0.119 total time=   0.0s
[CV 5/5] END C=1, epsilon=1, gamma=scale, kernel=rbf;, score=-0.137 total time=   0.0s
[CV 1/5] END C=1, epsilon=1, gamma=scale, kernel=poly;, score=-0.044 total time=   0.0s
[CV 2/5] END C=1, epsilon=1, gamma=scale, kernel=poly;, score=-0.013 total time=   0.0s
[CV 3/5] END C=1, epsilon=1, gamma=scale, kernel=poly;, score=-0.150 total time=   0.0s
[CV 4/5] END C=1, epsilon=1, gamma=scale, kernel=poly;, score=-0.112 total time=   0.0s
[CV 5/5] END C=1, epsilon=1, gamma=scale, kernel=poly;, score=-0.131 total time=   0.0s
[CV 1/5] END C=1, epsilon=1, gamma=scale, kernel=linear;, score=0.008 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=1, epsilon=1, gamma=scale, kernel=linear;, score=0.042 total time=   0.0s
[CV 3/5] END C=1, epsilon=1, gamma=scale, kernel=linear;, score=-0.100 total time=   0.0s
[CV 4/5] END C=1, epsilon=1, gamma=scale, kernel=linear;, score=-0.064 total time=   0.0s
[CV 5/5] END C=1, epsilon=1, gamma=scale, kernel=linear;, score=-0.085 total time=   0.0s
[CV 1/5] END C=1, epsilon=1, gamma=auto, kernel=rbf;, score=-0.049 total time=   0.0s
[CV 2/5] END C=1, epsilon=1, gamma=auto, kernel=rbf;, score=-0.019 total time=   0.0s
[CV 3/5] END C=1, epsilon=1, gamma=auto, kernel=rbf;, score=-0.157 total time=   0.0s
[CV 4/5] END C=1, epsilon=1, gamma=auto, kernel=rbf;, score=-0.119 total time=   0.0s
[CV 5/5] END C=1, epsilon=1, gamma=auto, kernel=rbf;, score=-0.137 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 1/5] END C=1, epsilon=1, gamma=auto, kernel=poly;, score=-0.044 total time=   0.0s
[CV 2/5] END C=1, epsilon=1, gamma=auto, kernel=poly;, score=-0.013 total time=   0.0s
[CV 3/5] END C=1, epsilon=1, gamma=auto, kernel=poly;, score=-0.150 total time=   0.0s
[CV 4/5] END C=1, epsilon=1, gamma=auto, kernel=poly;, score=-0.112 total time=   0.0s
[CV 5/5] END C=1, epsilon=1, gamma=auto, kernel=poly;, score=-0.132 total time=   0.0s
[CV 1/5] END C=1, epsilon=1, gamma=auto, kernel=linear;, score=0.008 total time=   0.0s
[CV 2/5] END C=1, epsilon=1, gamma=auto, kernel=linear;, score=0.042 total time=   0.0s
[CV 3/5] END C=1, epsilon=1, gamma=auto, kernel=linear;, score=-0.100 total time=   0.0s
[CV 4/5] END C=1, epsilon=1, gamma=auto, kernel=linear;, score=-0.064 total time=   0.0s
[CV 5/5] END C=1, epsilon=1, gamma=auto, kernel=linear;, score=-0.085 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.001, gamma=scale, kernel=rbf;, score=-0.004 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=10, epsilon=0.001, gamma=scale, kernel=rbf;, score=0.022 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.001, gamma=scale, kernel=rbf;, score=-0.119 total time=   0.0s
[CV 4/5] END C=10, epsilon=0.001, gamma=scale, kernel=rbf;, score=-0.083 total time=   0.0s
[CV 5/5] END C=10, epsilon=0.001, gamma=scale, kernel=rbf;, score=-0.104 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.001, gamma=scale, kernel=poly;, score=0.044 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.001, gamma=scale, kernel=poly;, score=0.080 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.001, gamma=scale, kernel=poly;, score=-0.059 total time=   0.0s
[CV 4/5] END C=10, epsilon=0.001, gamma=scale, kernel=poly;, score=-0.010 total time=   0.0s
[CV 5/5] END C=10, epsilon=0.001, gamma=scale, kernel=poly;, score=-0.050 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.001, gamma=scale, kernel=linear;, score=0.388 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=10, epsilon=0.001, gamma=scale, kernel=linear;, score=0.461 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.001, gamma=scale, kernel=linear;, score=0.288 total time=   0.0s
[CV 4/5] END C=10, epsilon=0.001, gamma=scale, kernel=linear;, score=0.340 total time=   0.0s
[CV 5/5] END C=10, epsilon=0.001, gamma=scale, kernel=linear;, score=0.298 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.001, gamma=auto, kernel=rbf;, score=-0.004 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.001, gamma=auto, kernel=rbf;, score=0.023 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.001, gamma=auto, kernel=rbf;, score=-0.119 total time=   0.0s
[CV 4/5] END C=10, epsilon=0.001, gamma=auto, kernel=rbf;, score=-0.083 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 5/5] END C=10, epsilon=0.001, gamma=auto, kernel=rbf;, score=-0.104 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.001, gamma=auto, kernel=poly;, score=0.047 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.001, gamma=auto, kernel=poly;, score=0.077 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.001, gamma=auto, kernel=poly;, score=-0.061 total time=   0.0s
[CV 4/5] END C=10, epsilon=0.001, gamma=auto, kernel=poly;, score=-0.010 total time=   0.0s
[CV 5/5] END C=10, epsilon=0.001, gamma=auto, kernel=poly;, score=-0.051 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.001, gamma=auto, kernel=linear;, score=0.388 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.001, gamma=auto, kernel=linear;, score=0.461 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.001, gamma=auto, kernel=linear;, score=0.288 total time=   0.0s
[CV 4/5] END C=10, epsilon=0.001, gamma=auto, kernel=linear;, score=0.340 total time=   0.0s
[CV 5/5] END C=10, epsilon=0.001, gamma=auto, kernel=linear;, score=0.298 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 1/5] END C=10, epsilon=0.01, gamma=scale, kernel=rbf;, score=-0.004 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.01, gamma=scale, kernel=rbf;, score=0.022 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.01, gamma=scale, kernel=rbf;, score=-0.119 total time=   0.0s
[CV 4/5] END C=10, epsilon=0.01, gamma=scale, kernel=rbf;, score=-0.083 total time=   0.0s
[CV 5/5] END C=10, epsilon=0.01, gamma=scale, kernel=rbf;, score=-0.104 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.01, gamma=scale, kernel=poly;, score=0.044 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.01, gamma=scale, kernel=poly;, score=0.080 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.01, gamma=scale, kernel=poly;, score=-0.059 total time=   0.0s
[CV 4/5] END C=10, epsilon=0.01, gamma=scale, kernel=poly;, score=-0.010 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 5/5] END C=10, epsilon=0.01, gamma=scale, kernel=poly;, score=-0.050 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.01, gamma=scale, kernel=linear;, score=0.388 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.01, gamma=scale, kernel=linear;, score=0.461 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.01, gamma=scale, kernel=linear;, score=0.288 total time=   0.0s
[CV 4/5] END C=10, epsilon=0.01, gamma=scale, kernel=linear;, score=0.340 total time=   0.0s
[CV 5/5] END C=10, epsilon=0.01, gamma=scale, kernel=linear;, score=0.298 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.01, gamma=auto, kernel=rbf;, score=-0.004 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.01, gamma=auto, kernel=rbf;, score=0.023 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.01, gamma=auto, kernel=rbf;, score=-0.119 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 4/5] END C=10, epsilon=0.01, gamma=auto, kernel=rbf;, score=-0.083 total time=   0.0s
[CV 5/5] END C=10, epsilon=0.01, gamma=auto, kernel=rbf;, score=-0.104 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.01, gamma=auto, kernel=poly;, score=0.047 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.01, gamma=auto, kernel=poly;, score=0.078 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.01, gamma=auto, kernel=poly;, score=-0.061 total time=   0.0s
[CV 4/5] END C=10, epsilon=0.01, gamma=auto, kernel=poly;, score=-0.010 total time=   0.0s
[CV 5/5] END C=10, epsilon=0.01, gamma=auto, kernel=poly;, score=-0.051 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.01, gamma=auto, kernel=linear;, score=0.388 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.01, gamma=auto, kernel=linear;, score=0.461 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.01, gamma=auto, kernel=linear;, score=0.288 total time=   0.0s
[CV 4/5] END C=10, epsilon=0.01, gamma=auto, kernel=linear;, score=0.340 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 5/5] END C=10, epsilon=0.01, gamma=auto, kernel=linear;, score=0.298 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.1, gamma=scale, kernel=rbf;, score=-0.004 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.1, gamma=scale, kernel=rbf;, score=0.022 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.1, gamma=scale, kernel=rbf;, score=-0.119 total time=   0.0s
[CV 4/5] END C=10, epsilon=0.1, gamma=scale, kernel=rbf;, score=-0.083 total time=   0.0s
[CV 5/5] END C=10, epsilon=0.1, gamma=scale, kernel=rbf;, score=-0.104 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.1, gamma=scale, kernel=poly;, score=0.044 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.1, gamma=scale, kernel=poly;, score=0.080 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.1, gamma=scale, kernel=poly;, score=-0.059 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 4/5] END C=10, epsilon=0.1, gamma=scale, kernel=poly;, score=-0.010 total time=   0.0s
[CV 5/5] END C=10, epsilon=0.1, gamma=scale, kernel=poly;, score=-0.050 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.1, gamma=scale, kernel=linear;, score=0.388 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.1, gamma=scale, kernel=linear;, score=0.461 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.1, gamma=scale, kernel=linear;, score=0.288 total time=   0.0s
[CV 4/5] END C=10, epsilon=0.1, gamma=scale, kernel=linear;, score=0.340 total time=   0.0s
[CV 5/5] END C=10, epsilon=0.1, gamma=scale, kernel=linear;, score=0.298 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.1, gamma=auto, kernel=rbf;, score=-0.004 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.1, gamma=auto, kernel=rbf;, score=0.023 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.1, gamma=auto, kernel=rbf;, score=-0.119 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 4/5] END C=10, epsilon=0.1, gamma=auto, kernel=rbf;, score=-0.083 total time=   0.0s
[CV 5/5] END C=10, epsilon=0.1, gamma=auto, kernel=rbf;, score=-0.104 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.1, gamma=auto, kernel=poly;, score=0.047 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.1, gamma=auto, kernel=poly;, score=0.078 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.1, gamma=auto, kernel=poly;, score=-0.061 total time=   0.0s
[CV 4/5] END C=10, epsilon=0.1, gamma=auto, kernel=poly;, score=-0.010 total time=   0.0s
[CV 5/5] END C=10, epsilon=0.1, gamma=auto, kernel=poly;, score=-0.051 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.1, gamma=auto, kernel=linear;, score=0.388 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.1, gamma=auto, kernel=linear;, score=0.461 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.1, gamma=auto, kernel=linear;, score=0.288 total time=   0.0s
[CV 4/5] END C=10, epsilon=0.1, gamma=auto, kernel=linear;, score=0.340 total time=   0.0s
[CV 5/5] END C=10, epsilon=0.1, gamma=auto, kernel=linear;, score=0.298 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 1/5] END C=10, epsilon=0.5, gamma=scale, kernel=rbf;, score=-0.004 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.5, gamma=scale, kernel=rbf;, score=0.022 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.5, gamma=scale, kernel=rbf;, score=-0.119 total time=   0.0s
[CV 4/5] END C=10, epsilon=0.5, gamma=scale, kernel=rbf;, score=-0.083 total time=   0.0s
[CV 5/5] END C=10, epsilon=0.5, gamma=scale, kernel=rbf;, score=-0.104 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.5, gamma=scale, kernel=poly;, score=0.044 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.5, gamma=scale, kernel=poly;, score=0.080 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.5, gamma=scale, kernel=poly;, score=-0.059 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 4/5] END C=10, epsilon=0.5, gamma=scale, kernel=poly;, score=-0.010 total time=   0.0s
[CV 5/5] END C=10, epsilon=0.5, gamma=scale, kernel=poly;, score=-0.050 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.5, gamma=scale, kernel=linear;, score=0.388 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.5, gamma=scale, kernel=linear;, score=0.461 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.5, gamma=scale, kernel=linear;, score=0.288 total time=   0.0s
[CV 4/5] END C=10, epsilon=0.5, gamma=scale, kernel=linear;, score=0.340 total time=   0.0s
[CV 5/5] END C=10, epsilon=0.5, gamma=scale, kernel=linear;, score=0.298 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.5, gamma=auto, kernel=rbf;, score=-0.004 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.5, gamma=auto, kernel=rbf;, score=0.023 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.5, gamma=auto, kernel=rbf;, score=-0.119 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 4/5] END C=10, epsilon=0.5, gamma=auto, kernel=rbf;, score=-0.083 total time=   0.0s
[CV 5/5] END C=10, epsilon=0.5, gamma=auto, kernel=rbf;, score=-0.104 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.5, gamma=auto, kernel=poly;, score=0.047 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.5, gamma=auto, kernel=poly;, score=0.078 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.5, gamma=auto, kernel=poly;, score=-0.061 total time=   0.0s
[CV 4/5] END C=10, epsilon=0.5, gamma=auto, kernel=poly;, score=-0.010 total time=   0.0s
[CV 5/5] END C=10, epsilon=0.5, gamma=auto, kernel=poly;, score=-0.051 total time=   0.0s
[CV 1/5] END C=10, epsilon=0.5, gamma=auto, kernel=linear;, score=0.388 total time=   0.0s
[CV 2/5] END C=10, epsilon=0.5, gamma=auto, kernel=linear;, score=0.461 total time=   0.0s
[CV 3/5] END C=10, epsilon=0.5, gamma=auto, kernel=linear;, score=0.288 total time=   0.0s
[CV 4/5] END C=10, epsilon=0.5, gamma=auto, kernel=linear;, score=0.340 total time=   0.0s
[CV 5/5] END C=10, epsilon=0.5, gamma=auto, kernel=linear;, score=0.298 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 1/5] END C=10, epsilon=1, gamma=scale, kernel=rbf;, score=-0.004 total time=   0.0s
[CV 2/5] END C=10, epsilon=1, gamma=scale, kernel=rbf;, score=0.022 total time=   0.0s
[CV 3/5] END C=10, epsilon=1, gamma=scale, kernel=rbf;, score=-0.119 total time=   0.0s
[CV 4/5] END C=10, epsilon=1, gamma=scale, kernel=rbf;, score=-0.083 total time=   0.0s
[CV 5/5] END C=10, epsilon=1, gamma=scale, kernel=rbf;, score=-0.104 total time=   0.0s
[CV 1/5] END C=10, epsilon=1, gamma=scale, kernel=poly;, score=0.044 total time=   0.0s
[CV 2/5] END C=10, epsilon=1, gamma=scale, kernel=poly;, score=0.080 total time=   0.0s
[CV 3/5] END C=10, epsilon=1, gamma=scale, kernel=poly;, score=-0.059 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 4/5] END C=10, epsilon=1, gamma=scale, kernel=poly;, score=-0.010 total time=   0.0s
[CV 5/5] END C=10, epsilon=1, gamma=scale, kernel=poly;, score=-0.050 total time=   0.0s
[CV 1/5] END C=10, epsilon=1, gamma=scale, kernel=linear;, score=0.388 total time=   0.0s
[CV 2/5] END C=10, epsilon=1, gamma=scale, kernel=linear;, score=0.461 total time=   0.0s
[CV 3/5] END C=10, epsilon=1, gamma=scale, kernel=linear;, score=0.288 total time=   0.0s
[CV 4/5] END C=10, epsilon=1, gamma=scale, kernel=linear;, score=0.340 total time=   0.0s
[CV 5/5] END C=10, epsilon=1, gamma=scale, kernel=linear;, score=0.298 total time=   0.0s
[CV 1/5] END C=10, epsilon=1, gamma=auto, kernel=rbf;, score=-0.004 total time=   0.0s
[CV 2/5] END C=10, epsilon=1, gamma=auto, kernel=rbf;, score=0.023 total time=   0.0s
[CV 3/5] END C=10, epsilon=1, gamma=auto, kernel=rbf;, score=-0.119 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 4/5] END C=10, epsilon=1, gamma=auto, kernel=rbf;, score=-0.083 total time=   0.0s
[CV 5/5] END C=10, epsilon=1, gamma=auto, kernel=rbf;, score=-0.104 total time=   0.0s
[CV 1/5] END C=10, epsilon=1, gamma=auto, kernel=poly;, score=0.047 total time=   0.0s
[CV 2/5] END C=10, epsilon=1, gamma=auto, kernel=poly;, score=0.078 total time=   0.0s
[CV 3/5] END C=10, epsilon=1, gamma=auto, kernel=poly;, score=-0.061 total time=   0.0s
[CV 4/5] END C=10, epsilon=1, gamma=auto, kernel=poly;, score=-0.010 total time=   0.0s
[CV 5/5] END C=10, epsilon=1, gamma=auto, kernel=poly;, score=-0.051 total time=   0.0s
[CV 1/5] END C=10, epsilon=1, gamma=auto, kernel=linear;, score=0.388 total time=   0.0s
[CV 2/5] END C=10, epsilon=1, gamma=auto, kernel=linear;, score=0.461 total time=   0.0s
[CV 3/5] END C=10, epsilon=1, gamma=auto, kernel=linear;, score=0.288 total time=   0.0s
[CV 4/5] END C=10, epsilon=1, gamma=auto, kernel=linear;, score=0.340 total time=   0.0s
[CV 5/5] END C=10, epsilon=1, gamma=auto, kernel=linear;, score=0.298 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 1/5] END C=100, epsilon=0.001, gamma=scale, kernel=rbf;, score=0.305 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.001, gamma=scale, kernel=rbf;, score=0.318 total time=   0.0s
[CV 3/5] END C=100, epsilon=0.001, gamma=scale, kernel=rbf;, score=0.155 total time=   0.0s
[CV 4/5] END C=100, epsilon=0.001, gamma=scale, kernel=rbf;, score=0.208 total time=   0.0s
[CV 5/5] END C=100, epsilon=0.001, gamma=scale, kernel=rbf;, score=0.161 total time=   0.0s
[CV 1/5] END C=100, epsilon=0.001, gamma=scale, kernel=poly;, score=0.529 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.001, gamma=scale, kernel=poly;, score=0.571 total time=   0.0s
[CV 3/5] END C=100, epsilon=0.001, gamma=scale, kernel=poly;, score=0.472 total time=   0.0s
[CV 4/5] END C=100, epsilon=0.001, gamma=scale, kernel=poly;, score=0.535 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 5/5] END C=100, epsilon=0.001, gamma=scale, kernel=poly;, score=0.416 total time=   0.0s
[CV 1/5] END C=100, epsilon=0.001, gamma=scale, kernel=linear;, score=0.596 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.001, gamma=scale, kernel=linear;, score=0.636 total time=   0.0s
[CV 3/5] END C=100, epsilon=0.001, gamma=scale, kernel=linear;, score=0.567 total time=   0.0s
[CV 4/5] END C=100, epsilon=0.001, gamma=scale, kernel=linear;, score=0.589 total time=   0.0s
[CV 5/5] END C=100, epsilon=0.001, gamma=scale, kernel=linear;, score=0.537 total time=   0.0s
[CV 1/5] END C=100, epsilon=0.001, gamma=auto, kernel=rbf;, score=0.303 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.001, gamma=auto, kernel=rbf;, score=0.319 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 3/5] END C=100, epsilon=0.001, gamma=auto, kernel=rbf;, score=0.156 total time=   0.0s
[CV 4/5] END C=100, epsilon=0.001, gamma=auto, kernel=rbf;, score=0.208 total time=   0.0s
[CV 5/5] END C=100, epsilon=0.001, gamma=auto, kernel=rbf;, score=0.161 total time=   0.0s
[CV 1/5] END C=100, epsilon=0.001, gamma=auto, kernel=poly;, score=0.539 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.001, gamma=auto, kernel=poly;, score=0.565 total time=   0.0s
[CV 3/5] END C=100, epsilon=0.001, gamma=auto, kernel=poly;, score=0.468 total time=   0.0s
[CV 4/5] END C=100, epsilon=0.001, gamma=auto, kernel=poly;, score=0.536 total time=   0.0s
[CV 5/5] END C=100, epsilon=0.001, gamma=auto, kernel=poly;, score=0.414 total time=   0.0s
[CV 1/5] END C=100, epsilon=0.001, gamma=auto, kernel=linear;, score=0.596 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=100, epsilon=0.001, gamma=auto, kernel=linear;, score=0.636 total time=   0.0s
[CV 3/5] END C=100, epsilon=0.001, gamma=auto, kernel=linear;, score=0.567 total time=   0.0s
[CV 4/5] END C=100, epsilon=0.001, gamma=auto, kernel=linear;, score=0.589 total time=   0.0s
[CV 5/5] END C=100, epsilon=0.001, gamma=auto, kernel=linear;, score=0.537 total time=   0.0s
[CV 1/5] END C=100, epsilon=0.01, gamma=scale, kernel=rbf;, score=0.305 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.01, gamma=scale, kernel=rbf;, score=0.318 total time=   0.0s
[CV 3/5] END C=100, epsilon=0.01, gamma=scale, kernel=rbf;, score=0.155 total time=   0.0s
[CV 4/5] END C=100, epsilon=0.01, gamma=scale, kernel=rbf;, score=0.208 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 5/5] END C=100, epsilon=0.01, gamma=scale, kernel=rbf;, score=0.161 total time=   0.0s
[CV 1/5] END C=100, epsilon=0.01, gamma=scale, kernel=poly;, score=0.529 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.01, gamma=scale, kernel=poly;, score=0.571 total time=   0.0s
[CV 3/5] END C=100, epsilon=0.01, gamma=scale, kernel=poly;, score=0.472 total time=   0.0s
[CV 4/5] END C=100, epsilon=0.01, gamma=scale, kernel=poly;, score=0.535 total time=   0.0s
[CV 5/5] END C=100, epsilon=0.01, gamma=scale, kernel=poly;, score=0.416 total time=   0.0s
[CV 1/5] END C=100, epsilon=0.01, gamma=scale, kernel=linear;, score=0.596 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.01, gamma=scale, kernel=linear;, score=0.636 total time=   0.0s
[CV 3/5] END C=100, epsilon=0.01, gamma=scale, kernel=linear;, score=0.567 total time=   0.0s
[CV 4/5] END C=100, epsilon=0.01, gamma=scale, kernel=linear;, score=0.589 total time=   0.0s
[CV 5/5] END C=100, epsilon=0.01, gamma=scale, kernel=linear;, score=0.537 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 1/5] END C=100, epsilon=0.01, gamma=auto, kernel=rbf;, score=0.303 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.01, gamma=auto, kernel=rbf;, score=0.319 total time=   0.0s
[CV 3/5] END C=100, epsilon=0.01, gamma=auto, kernel=rbf;, score=0.156 total time=   0.0s
[CV 4/5] END C=100, epsilon=0.01, gamma=auto, kernel=rbf;, score=0.208 total time=   0.0s
[CV 5/5] END C=100, epsilon=0.01, gamma=auto, kernel=rbf;, score=0.161 total time=   0.0s
[CV 1/5] END C=100, epsilon=0.01, gamma=auto, kernel=poly;, score=0.539 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.01, gamma=auto, kernel=poly;, score=0.565 total time=   0.0s
[CV 3/5] END C=100, epsilon=0.01, gamma=auto, kernel=poly;, score=0.468 total time=   0.0s
[CV 4/5] END C=100, epsilon=0.01, gamma=auto, kernel=poly;, score=0.536 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 5/5] END C=100, epsilon=0.01, gamma=auto, kernel=poly;, score=0.414 total time=   0.0s
[CV 1/5] END C=100, epsilon=0.01, gamma=auto, kernel=linear;, score=0.596 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.01, gamma=auto, kernel=linear;, score=0.636 total time=   0.0s
[CV 3/5] END C=100, epsilon=0.01, gamma=auto, kernel=linear;, score=0.567 total time=   0.0s
[CV 4/5] END C=100, epsilon=0.01, gamma=auto, kernel=linear;, score=0.589 total time=   0.0s
[CV 5/5] END C=100, epsilon=0.01, gamma=auto, kernel=linear;, score=0.537 total time=   0.0s
[CV 1/5] END C=100, epsilon=0.1, gamma=scale, kernel=rbf;, score=0.305 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.1, gamma=scale, kernel=rbf;, score=0.318 total time=   0.0s
[CV 3/5] END C=100, epsilon=0.1, gamma=scale, kernel=rbf;, score=0.156 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 4/5] END C=100, epsilon=0.1, gamma=scale, kernel=rbf;, score=0.208 total time=   0.0s
[CV 5/5] END C=100, epsilon=0.1, gamma=scale, kernel=rbf;, score=0.161 total time=   0.0s
[CV 1/5] END C=100, epsilon=0.1, gamma=scale, kernel=poly;, score=0.529 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.1, gamma=scale, kernel=poly;, score=0.571 total time=   0.0s
[CV 3/5] END C=100, epsilon=0.1, gamma=scale, kernel=poly;, score=0.472 total time=   0.0s
[CV 4/5] END C=100, epsilon=0.1, gamma=scale, kernel=poly;, score=0.535 total time=   0.0s
[CV 5/5] END C=100, epsilon=0.1, gamma=scale, kernel=poly;, score=0.416 total time=   0.0s
[CV 1/5] END C=100, epsilon=0.1, gamma=scale, kernel=linear;, score=0.596 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.1, gamma=scale, kernel=linear;, score=0.636 total time=   0.0s
[CV 3/5] END C=100, epsilon=0.1, gamma=scale, kernel=linear;, score=0.567 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 4/5] END C=100, epsilon=0.1, gamma=scale, kernel=linear;, score=0.589 total time=   0.0s
[CV 5/5] END C=100, epsilon=0.1, gamma=scale, kernel=linear;, score=0.537 total time=   0.0s
[CV 1/5] END C=100, epsilon=0.1, gamma=auto, kernel=rbf;, score=0.303 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.1, gamma=auto, kernel=rbf;, score=0.319 total time=   0.0s
[CV 3/5] END C=100, epsilon=0.1, gamma=auto, kernel=rbf;, score=0.156 total time=   0.0s
[CV 4/5] END C=100, epsilon=0.1, gamma=auto, kernel=rbf;, score=0.208 total time=   0.0s
[CV 5/5] END C=100, epsilon=0.1, gamma=auto, kernel=rbf;, score=0.161 total time=   0.0s
[CV 1/5] END C=100, epsilon=0.1, gamma=auto, kernel=poly;, score=0.539 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.1, gamma=auto, kernel=poly;, score=0.565 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 3/5] END C=100, epsilon=0.1, gamma=auto, kernel=poly;, score=0.468 total time=   0.0s
[CV 4/5] END C=100, epsilon=0.1, gamma=auto, kernel=poly;, score=0.536 total time=   0.0s
[CV 5/5] END C=100, epsilon=0.1, gamma=auto, kernel=poly;, score=0.414 total time=   0.0s
[CV 1/5] END C=100, epsilon=0.1, gamma=auto, kernel=linear;, score=0.596 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.1, gamma=auto, kernel=linear;, score=0.636 total time=   0.0s
[CV 3/5] END C=100, epsilon=0.1, gamma=auto, kernel=linear;, score=0.567 total time=   0.0s
[CV 4/5] END C=100, epsilon=0.1, gamma=auto, kernel=linear;, score=0.589 total time=   0.0s
[CV 5/5] END C=100, epsilon=0.1, gamma=auto, kernel=linear;, score=0.537 total time=   0.0s
[CV 1/5] END C=100, epsilon=0.5, gamma=scale, kernel=rbf;, score=0.305 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=100, epsilon=0.5, gamma=scale, kernel=rbf;, score=0.318 total time=   0.0s
[CV 3/5] END C=100, epsilon=0.5, gamma=scale, kernel=rbf;, score=0.156 total time=   0.0s
[CV 4/5] END C=100, epsilon=0.5, gamma=scale, kernel=rbf;, score=0.208 total time=   0.0s
[CV 5/5] END C=100, epsilon=0.5, gamma=scale, kernel=rbf;, score=0.161 total time=   0.0s
[CV 1/5] END C=100, epsilon=0.5, gamma=scale, kernel=poly;, score=0.529 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.5, gamma=scale, kernel=poly;, score=0.571 total time=   0.0s
[CV 3/5] END C=100, epsilon=0.5, gamma=scale, kernel=poly;, score=0.472 total time=   0.0s
[CV 4/5] END C=100, epsilon=0.5, gamma=scale, kernel=poly;, score=0.535 total time=   0.0s
[CV 5/5] END C=100, epsilon=0.5, gamma=scale, kernel=poly;, score=0.416 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 1/5] END C=100, epsilon=0.5, gamma=scale, kernel=linear;, score=0.596 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.5, gamma=scale, kernel=linear;, score=0.636 total time=   0.0s
[CV 3/5] END C=100, epsilon=0.5, gamma=scale, kernel=linear;, score=0.567 total time=   0.0s
[CV 4/5] END C=100, epsilon=0.5, gamma=scale, kernel=linear;, score=0.589 total time=   0.0s
[CV 5/5] END C=100, epsilon=0.5, gamma=scale, kernel=linear;, score=0.537 total time=   0.0s
[CV 1/5] END C=100, epsilon=0.5, gamma=auto, kernel=rbf;, score=0.303 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.5, gamma=auto, kernel=rbf;, score=0.319 total time=   0.0s
[CV 3/5] END C=100, epsilon=0.5, gamma=auto, kernel=rbf;, score=0.156 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 4/5] END C=100, epsilon=0.5, gamma=auto, kernel=rbf;, score=0.208 total time=   0.0s
[CV 5/5] END C=100, epsilon=0.5, gamma=auto, kernel=rbf;, score=0.161 total time=   0.0s
[CV 1/5] END C=100, epsilon=0.5, gamma=auto, kernel=poly;, score=0.539 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.5, gamma=auto, kernel=poly;, score=0.565 total time=   0.0s
[CV 3/5] END C=100, epsilon=0.5, gamma=auto, kernel=poly;, score=0.468 total time=   0.0s
[CV 4/5] END C=100, epsilon=0.5, gamma=auto, kernel=poly;, score=0.536 total time=   0.0s
[CV 5/5] END C=100, epsilon=0.5, gamma=auto, kernel=poly;, score=0.414 total time=   0.0s
[CV 1/5] END C=100, epsilon=0.5, gamma=auto, kernel=linear;, score=0.596 total time=   0.0s
[CV 2/5] END C=100, epsilon=0.5, gamma=auto, kernel=linear;, score=0.636 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 3/5] END C=100, epsilon=0.5, gamma=auto, kernel=linear;, score=0.567 total time=   0.0s
[CV 4/5] END C=100, epsilon=0.5, gamma=auto, kernel=linear;, score=0.589 total time=   0.0s
[CV 5/5] END C=100, epsilon=0.5, gamma=auto, kernel=linear;, score=0.537 total time=   0.0s
[CV 1/5] END C=100, epsilon=1, gamma=scale, kernel=rbf;, score=0.305 total time=   0.0s
[CV 2/5] END C=100, epsilon=1, gamma=scale, kernel=rbf;, score=0.318 total time=   0.0s
[CV 3/5] END C=100, epsilon=1, gamma=scale, kernel=rbf;, score=0.156 total time=   0.0s
[CV 4/5] END C=100, epsilon=1, gamma=scale, kernel=rbf;, score=0.208 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 5/5] END C=100, epsilon=1, gamma=scale, kernel=rbf;, score=0.161 total time=   0.0s
[CV 1/5] END C=100, epsilon=1, gamma=scale, kernel=poly;, score=0.529 total time=   0.0s
[CV 2/5] END C=100, epsilon=1, gamma=scale, kernel=poly;, score=0.571 total time=   0.0s
[CV 3/5] END C=100, epsilon=1, gamma=scale, kernel=poly;, score=0.472 total time=   0.0s
[CV 4/5] END C=100, epsilon=1, gamma=scale, kernel=poly;, score=0.535 total time=   0.0s
[CV 5/5] END C=100, epsilon=1, gamma=scale, kernel=poly;, score=0.416 total time=   0.0s
[CV 1/5] END C=100, epsilon=1, gamma=scale, kernel=linear;, score=0.596 total time=   0.0s
[CV 2/5] END C=100, epsilon=1, gamma=scale, kernel=linear;, score=0.636 total time=   0.0s
[CV 3/5] END C=100, epsilon=1, gamma=scale, kernel=linear;, score=0.567 total time=   0.0s
[CV 4/5] END C=100, epsilon=1, gamma=scale, kernel=linear;, score=0.589 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 5/5] END C=100, epsilon=1, gamma=scale, kernel=linear;, score=0.537 total time=   0.0s
[CV 1/5] END C=100, epsilon=1, gamma=auto, kernel=rbf;, score=0.303 total time=   0.0s
[CV 2/5] END C=100, epsilon=1, gamma=auto, kernel=rbf;, score=0.319 total time=   0.0s
[CV 3/5] END C=100, epsilon=1, gamma=auto, kernel=rbf;, score=0.156 total time=   0.0s
[CV 4/5] END C=100, epsilon=1, gamma=auto, kernel=rbf;, score=0.208 total time=   0.0s
[CV 5/5] END C=100, epsilon=1, gamma=auto, kernel=rbf;, score=0.161 total time=   0.0s
[CV 1/5] END C=100, epsilon=1, gamma=auto, kernel=poly;, score=0.539 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=100, epsilon=1, gamma=auto, kernel=poly;, score=0.565 total time=   0.0s
[CV 3/5] END C=100, epsilon=1, gamma=auto, kernel=poly;, score=0.468 total time=   0.0s
[CV 4/5] END C=100, epsilon=1, gamma=auto, kernel=poly;, score=0.536 total time=   0.0s
[CV 5/5] END C=100, epsilon=1, gamma=auto, kernel=poly;, score=0.414 total time=   0.0s
[CV 1/5] END C=100, epsilon=1, gamma=auto, kernel=linear;, score=0.596 total time=   0.0s
[CV 2/5] END C=100, epsilon=1, gamma=auto, kernel=linear;, score=0.636 total time=   0.0s
[CV 3/5] END C=100, epsilon=1, gamma=auto, kernel=linear;, score=0.567 total time=   0.0s
[CV 4/5] END C=100, epsilon=1, gamma=auto, kernel=linear;, score=0.589 total time=   0.0s
[CV 5/5] END C=100, epsilon=1, gamma=auto, kernel=linear;, score=0.537 total time=   0.0s
[CV 1/5] END C=1000, epsilon=0.001, gamma=scale, kernel=rbf;, score=0.733 total time=   0.0s
[CV 2/5] END C=1000, epsilon=0.001, gamma=scale, kernel=rbf;, score=0.717 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.001, gamma=scale, kernel=rbf;, score=0.687 total time=   0.0s
[CV 4/5] END C=1000, epsilon=0.001, gamma=scale, kernel=rbf;, score=0.709 total time=   0.0s
[CV 5/5] END C=1000, epsilon=0.001, gamma=scale, kernel=rbf;, score=0.612 total time=   0.0s
[CV 1/5] END C=1000, epsilon=0.001, gamma=scale, kernel=poly;, score=0.800 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=1000, epsilon=0.001, gamma=scale, kernel=poly;, score=0.788 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.001, gamma=scale, kernel=poly;, score=0.825 total time=   0.0s
[CV 4/5] END C=1000, epsilon=0.001, gamma=scale, kernel=poly;, score=0.809 total time=   0.0s
[CV 5/5] END C=1000, epsilon=0.001, gamma=scale, kernel=poly;, score=0.724 total time=   0.0s
[CV 1/5] END C=1000, epsilon=0.001, gamma=scale, kernel=linear;, score=0.686 total time=   0.0s
[CV 2/5] END C=1000, epsilon=0.001, gamma=scale, kernel=linear;, score=0.598 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.001, gamma=scale, kernel=linear;, score=0.586 total time=   0.0s
[CV 4/5] END C=1000, epsilon=0.001, gamma=scale, kernel=linear;, score=0.574 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 5/5] END C=1000, epsilon=0.001, gamma=scale, kernel=linear;, score=0.556 total time=   0.0s
[CV 1/5] END C=1000, epsilon=0.001, gamma=auto, kernel=rbf;, score=0.732 total time=   0.0s
[CV 2/5] END C=1000, epsilon=0.001, gamma=auto, kernel=rbf;, score=0.717 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.001, gamma=auto, kernel=rbf;, score=0.688 total time=   0.0s
[CV 4/5] END C=1000, epsilon=0.001, gamma=auto, kernel=rbf;, score=0.709 total time=   0.0s
[CV 5/5] END C=1000, epsilon=0.001, gamma=auto, kernel=rbf;, score=0.612 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 1/5] END C=1000, epsilon=0.001, gamma=auto, kernel=poly;, score=0.802 total time=   0.0s
[CV 2/5] END C=1000, epsilon=0.001, gamma=auto, kernel=poly;, score=0.788 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.001, gamma=auto, kernel=poly;, score=0.823 total time=   0.0s
[CV 4/5] END C=1000, epsilon=0.001, gamma=auto, kernel=poly;, score=0.809 total time=   0.0s
[CV 5/5] END C=1000, epsilon=0.001, gamma=auto, kernel=poly;, score=0.724 total time=   0.0s
[CV 1/5] END C=1000, epsilon=0.001, gamma=auto, kernel=linear;, score=0.686 total time=   0.0s
[CV 2/5] END C=1000, epsilon=0.001, gamma=auto, kernel=linear;, score=0.598 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.001, gamma=auto, kernel=linear;, score=0.586 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 4/5] END C=1000, epsilon=0.001, gamma=auto, kernel=linear;, score=0.574 total time=   0.0s
[CV 5/5] END C=1000, epsilon=0.001, gamma=auto, kernel=linear;, score=0.556 total time=   0.0s
[CV 1/5] END C=1000, epsilon=0.01, gamma=scale, kernel=rbf;, score=0.733 total time=   0.0s
[CV 2/5] END C=1000, epsilon=0.01, gamma=scale, kernel=rbf;, score=0.717 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.01, gamma=scale, kernel=rbf;, score=0.687 total time=   0.0s
[CV 4/5] END C=1000, epsilon=0.01, gamma=scale, kernel=rbf;, score=0.709 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 5/5] END C=1000, epsilon=0.01, gamma=scale, kernel=rbf;, score=0.612 total time=   0.0s
[CV 1/5] END C=1000, epsilon=0.01, gamma=scale, kernel=poly;, score=0.800 total time=   0.0s
[CV 2/5] END C=1000, epsilon=0.01, gamma=scale, kernel=poly;, score=0.788 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.01, gamma=scale, kernel=poly;, score=0.825 total time=   0.0s
[CV 4/5] END C=1000, epsilon=0.01, gamma=scale, kernel=poly;, score=0.809 total time=   0.0s
[CV 5/5] END C=1000, epsilon=0.01, gamma=scale, kernel=poly;, score=0.724 total time=   0.0s
[CV 1/5] END C=1000, epsilon=0.01, gamma=scale, kernel=linear;, score=0.686 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=1000, epsilon=0.01, gamma=scale, kernel=linear;, score=0.598 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.01, gamma=scale, kernel=linear;, score=0.586 total time=   0.0s
[CV 4/5] END C=1000, epsilon=0.01, gamma=scale, kernel=linear;, score=0.574 total time=   0.0s
[CV 5/5] END C=1000, epsilon=0.01, gamma=scale, kernel=linear;, score=0.556 total time=   0.0s
[CV 1/5] END C=1000, epsilon=0.01, gamma=auto, kernel=rbf;, score=0.732 total time=   0.0s
[CV 2/5] END C=1000, epsilon=0.01, gamma=auto, kernel=rbf;, score=0.717 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 3/5] END C=1000, epsilon=0.01, gamma=auto, kernel=rbf;, score=0.688 total time=   0.0s
[CV 4/5] END C=1000, epsilon=0.01, gamma=auto, kernel=rbf;, score=0.709 total time=   0.0s
[CV 5/5] END C=1000, epsilon=0.01, gamma=auto, kernel=rbf;, score=0.612 total time=   0.0s
[CV 1/5] END C=1000, epsilon=0.01, gamma=auto, kernel=poly;, score=0.802 total time=   0.0s
[CV 2/5] END C=1000, epsilon=0.01, gamma=auto, kernel=poly;, score=0.788 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.01, gamma=auto, kernel=poly;, score=0.823 total time=   0.0s
[CV 4/5] END C=1000, epsilon=0.01, gamma=auto, kernel=poly;, score=0.809 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 5/5] END C=1000, epsilon=0.01, gamma=auto, kernel=poly;, score=0.724 total time=   0.0s
[CV 1/5] END C=1000, epsilon=0.01, gamma=auto, kernel=linear;, score=0.686 total time=   0.0s
[CV 2/5] END C=1000, epsilon=0.01, gamma=auto, kernel=linear;, score=0.598 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.01, gamma=auto, kernel=linear;, score=0.586 total time=   0.0s
[CV 4/5] END C=1000, epsilon=0.01, gamma=auto, kernel=linear;, score=0.574 total time=   0.0s
[CV 5/5] END C=1000, epsilon=0.01, gamma=auto, kernel=linear;, score=0.556 total time=   0.0s
[CV 1/5] END C=1000, epsilon=0.1, gamma=scale, kernel=rbf;, score=0.733 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=1000, epsilon=0.1, gamma=scale, kernel=rbf;, score=0.717 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.1, gamma=scale, kernel=rbf;, score=0.687 total time=   0.0s
[CV 4/5] END C=1000, epsilon=0.1, gamma=scale, kernel=rbf;, score=0.709 total time=   0.0s
[CV 5/5] END C=1000, epsilon=0.1, gamma=scale, kernel=rbf;, score=0.612 total time=   0.0s
[CV 1/5] END C=1000, epsilon=0.1, gamma=scale, kernel=poly;, score=0.800 total time=   0.0s
[CV 2/5] END C=1000, epsilon=0.1, gamma=scale, kernel=poly;, score=0.788 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.1, gamma=scale, kernel=poly;, score=0.825 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 4/5] END C=1000, epsilon=0.1, gamma=scale, kernel=poly;, score=0.809 total time=   0.0s
[CV 5/5] END C=1000, epsilon=0.1, gamma=scale, kernel=poly;, score=0.724 total time=   0.0s
[CV 1/5] END C=1000, epsilon=0.1, gamma=scale, kernel=linear;, score=0.686 total time=   0.0s
[CV 2/5] END C=1000, epsilon=0.1, gamma=scale, kernel=linear;, score=0.598 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.1, gamma=scale, kernel=linear;, score=0.586 total time=   0.0s
[CV 4/5] END C=1000, epsilon=0.1, gamma=scale, kernel=linear;, score=0.574 total time=   0.0s
[CV 5/5] END C=1000, epsilon=0.1, gamma=scale, kernel=linear;, score=0.556 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 1/5] END C=1000, epsilon=0.1, gamma=auto, kernel=rbf;, score=0.732 total time=   0.0s
[CV 2/5] END C=1000, epsilon=0.1, gamma=auto, kernel=rbf;, score=0.717 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.1, gamma=auto, kernel=rbf;, score=0.688 total time=   0.0s
[CV 4/5] END C=1000, epsilon=0.1, gamma=auto, kernel=rbf;, score=0.709 total time=   0.0s
[CV 5/5] END C=1000, epsilon=0.1, gamma=auto, kernel=rbf;, score=0.612 total time=   0.0s
[CV 1/5] END C=1000, epsilon=0.1, gamma=auto, kernel=poly;, score=0.802 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=1000, epsilon=0.1, gamma=auto, kernel=poly;, score=0.788 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.1, gamma=auto, kernel=poly;, score=0.823 total time=   0.0s
[CV 4/5] END C=1000, epsilon=0.1, gamma=auto, kernel=poly;, score=0.809 total time=   0.0s
[CV 5/5] END C=1000, epsilon=0.1, gamma=auto, kernel=poly;, score=0.724 total time=   0.0s
[CV 1/5] END C=1000, epsilon=0.1, gamma=auto, kernel=linear;, score=0.686 total time=   0.0s
[CV 2/5] END C=1000, epsilon=0.1, gamma=auto, kernel=linear;, score=0.598 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.1, gamma=auto, kernel=linear;, score=0.586 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 4/5] END C=1000, epsilon=0.1, gamma=auto, kernel=linear;, score=0.574 total time=   0.0s
[CV 5/5] END C=1000, epsilon=0.1, gamma=auto, kernel=linear;, score=0.556 total time=   0.0s
[CV 1/5] END C=1000, epsilon=0.5, gamma=scale, kernel=rbf;, score=0.733 total time=   0.0s
[CV 2/5] END C=1000, epsilon=0.5, gamma=scale, kernel=rbf;, score=0.717 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.5, gamma=scale, kernel=rbf;, score=0.687 total time=   0.0s
[CV 4/5] END C=1000, epsilon=0.5, gamma=scale, kernel=rbf;, score=0.709 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 5/5] END C=1000, epsilon=0.5, gamma=scale, kernel=rbf;, score=0.612 total time=   0.0s
[CV 1/5] END C=1000, epsilon=0.5, gamma=scale, kernel=poly;, score=0.800 total time=   0.0s
[CV 2/5] END C=1000, epsilon=0.5, gamma=scale, kernel=poly;, score=0.788 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.5, gamma=scale, kernel=poly;, score=0.825 total time=   0.0s
[CV 4/5] END C=1000, epsilon=0.5, gamma=scale, kernel=poly;, score=0.809 total time=   0.0s
[CV 5/5] END C=1000, epsilon=0.5, gamma=scale, kernel=poly;, score=0.724 total time=   0.0s
[CV 1/5] END C=1000, epsilon=0.5, gamma=scale, kernel=linear;, score=0.686 total time=   0.0s
[CV 2/5] END C=1000, epsilon=0.5, gamma=scale, kernel=linear;, score=0.598 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 3/5] END C=1000, epsilon=0.5, gamma=scale, kernel=linear;, score=0.586 total time=   0.0s
[CV 4/5] END C=1000, epsilon=0.5, gamma=scale, kernel=linear;, score=0.574 total time=   0.0s
[CV 5/5] END C=1000, epsilon=0.5, gamma=scale, kernel=linear;, score=0.556 total time=   0.0s
[CV 1/5] END C=1000, epsilon=0.5, gamma=auto, kernel=rbf;, score=0.732 total time=   0.0s
[CV 2/5] END C=1000, epsilon=0.5, gamma=auto, kernel=rbf;, score=0.717 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.5, gamma=auto, kernel=rbf;, score=0.688 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 4/5] END C=1000, epsilon=0.5, gamma=auto, kernel=rbf;, score=0.709 total time=   0.0s
[CV 5/5] END C=1000, epsilon=0.5, gamma=auto, kernel=rbf;, score=0.612 total time=   0.0s
[CV 1/5] END C=1000, epsilon=0.5, gamma=auto, kernel=poly;, score=0.802 total time=   0.0s
[CV 2/5] END C=1000, epsilon=0.5, gamma=auto, kernel=poly;, score=0.788 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.5, gamma=auto, kernel=poly;, score=0.823 total time=   0.0s
[CV 4/5] END C=1000, epsilon=0.5, gamma=auto, kernel=poly;, score=0.809 total time=   0.0s
[CV 5/5] END C=1000, epsilon=0.5, gamma=auto, kernel=poly;, score=0.724 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 1/5] END C=1000, epsilon=0.5, gamma=auto, kernel=linear;, score=0.686 total time=   0.0s
[CV 2/5] END C=1000, epsilon=0.5, gamma=auto, kernel=linear;, score=0.598 total time=   0.0s
[CV 3/5] END C=1000, epsilon=0.5, gamma=auto, kernel=linear;, score=0.586 total time=   0.0s
[CV 4/5] END C=1000, epsilon=0.5, gamma=auto, kernel=linear;, score=0.574 total time=   0.0s
[CV 5/5] END C=1000, epsilon=0.5, gamma=auto, kernel=linear;, score=0.556 total time=   0.0s
[CV 1/5] END C=1000, epsilon=1, gamma=scale, kernel=rbf;, score=0.733 total time=   0.0s
[CV 2/5] END C=1000, epsilon=1, gamma=scale, kernel=rbf;, score=0.717 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 3/5] END C=1000, epsilon=1, gamma=scale, kernel=rbf;, score=0.687 total time=   0.0s
[CV 4/5] END C=1000, epsilon=1, gamma=scale, kernel=rbf;, score=0.709 total time=   0.0s
[CV 5/5] END C=1000, epsilon=1, gamma=scale, kernel=rbf;, score=0.612 total time=   0.0s
[CV 1/5] END C=1000, epsilon=1, gamma=scale, kernel=poly;, score=0.800 total time=   0.0s
[CV 2/5] END C=1000, epsilon=1, gamma=scale, kernel=poly;, score=0.788 total time=   0.0s
[CV 3/5] END C=1000, epsilon=1, gamma=scale, kernel=poly;, score=0.825 total time=   0.0s
[CV 4/5] END C=1000, epsilon=1, gamma=scale, kernel=poly;, score=0.809 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 5/5] END C=1000, epsilon=1, gamma=scale, kernel=poly;, score=0.724 total time=   0.0s
[CV 1/5] END C=1000, epsilon=1, gamma=scale, kernel=linear;, score=0.686 total time=   0.0s
[CV 2/5] END C=1000, epsilon=1, gamma=scale, kernel=linear;, score=0.598 total time=   0.0s
[CV 3/5] END C=1000, epsilon=1, gamma=scale, kernel=linear;, score=0.586 total time=   0.0s
[CV 4/5] END C=1000, epsilon=1, gamma=scale, kernel=linear;, score=0.574 total time=   0.0s
[CV 5/5] END C=1000, epsilon=1, gamma=scale, kernel=linear;, score=0.556 total time=   0.0s
[CV 1/5] END C=1000, epsilon=1, gamma=auto, kernel=rbf;, score=0.732 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END C=1000, epsilon=1, gamma=auto, kernel=rbf;, score=0.717 total time=   0.0s
[CV 3/5] END C=1000, epsilon=1, gamma=auto, kernel=rbf;, score=0.688 total time=   0.0s
[CV 4/5] END C=1000, epsilon=1, gamma=auto, kernel=rbf;, score=0.709 total time=   0.0s
[CV 5/5] END C=1000, epsilon=1, gamma=auto, kernel=rbf;, score=0.612 total time=   0.0s
[CV 1/5] END C=1000, epsilon=1, gamma=auto, kernel=poly;, score=0.802 total time=   0.0s
[CV 2/5] END C=1000, epsilon=1, gamma=auto, kernel=poly;, score=0.788 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 3/5] END C=1000, epsilon=1, gamma=auto, kernel=poly;, score=0.823 total time=   0.0s
[CV 4/5] END C=1000, epsilon=1, gamma=auto, kernel=poly;, score=0.809 total time=   0.0s
[CV 5/5] END C=1000, epsilon=1, gamma=auto, kernel=poly;, score=0.724 total time=   0.0s
[CV 1/5] END C=1000, epsilon=1, gamma=auto, kernel=linear;, score=0.686 total time=   0.0s
[CV 2/5] END C=1000, epsilon=1, gamma=auto, kernel=linear;, score=0.598 total time=   0.0s
[CV 3/5] END C=1000, epsilon=1, gamma=auto, kernel=linear;, score=0.586 total time=   0.0s
[CV 4/5] END C=1000, epsilon=1, gamma=auto, kernel=linear;, score=0.574 total time=   0.0s
[CV 5/5] END C=1000, epsilon=1, gamma=auto, kernel=linear;, score=0.556 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=1,
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'epsilon': [0.001, 0.01, 0.1, 0.5, 1],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['rbf', 'poly', 'linear']},
             verbose=3)

In [13]:
print("The R score value for the best parameter {}".format(grid.best_params_))

The R score value for the best parameter {'C': 1000, 'epsilon': 0.01, 'gamma': 'auto', 'kernel': 'poly'}

In [14]:
re = grid.cv_results_

In [15]:
table = pd.DataFrame.from_dict(re)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_epsilon,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.020752,0.001176,0.011961,6.417871e-04,0.1,0.001,scale,rbf,"{'C': 0.1, 'epsilon': 0.001, 'gamma': 'scale',...",-0.053773,-0.023184,-0.159754,-0.122633,-0.140910,-0.100051,0.052524,148
1,0.016143,0.001711,0.003596,8.041297e-04,0.1,0.001,scale,poly,"{'C': 0.1, 'epsilon': 0.001, 'gamma': 'scale',...",-0.053215,-0.022556,-0.159064,-0.121889,-0.140331,-0.099411,0.052496,133
2,0.014168,0.000394,0.002999,1.209006e-05,0.1,0.001,scale,linear,"{'C': 0.1, 'epsilon': 0.001, 'gamma': 'scale',...",-0.047853,-0.017086,-0.155056,-0.116734,-0.135275,-0.094401,0.052901,111
3,0.021343,0.002223,0.012176,9.875293e-04,0.1,0.001,auto,rbf,"{'C': 0.1, 'epsilon': 0.001, 'gamma': 'auto', ...",-0.053776,-0.023183,-0.159753,-0.122633,-0.140910,-0.100051,0.052524,141
4,0.013963,0.000001,0.002991,8.792443e-07,0.1,0.001,auto,poly,"{'C': 0.1, 'epsilon': 0.001, 'gamma': 'auto', ...",-0.053174,-0.022581,-0.159077,-0.121887,-0.140338,-0.099411,0.052500,136
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,0.026130,0.002766,0.003391,4.888893e-04,1000.0,1.000,scale,poly,"{'C': 1000, 'epsilon': 1, 'gamma': 'scale', 'k...",0.800147,0.788344,0.824735,0.809299,0.724354,0.789376,0.034618,10
146,0.025861,0.000729,0.003002,1.668549e-05,1000.0,1.000,scale,linear,"{'C': 1000, 'epsilon': 1, 'gamma': 'scale', 'k...",0.686122,0.598327,0.585690,0.573965,0.555772,0.599975,0.045296,23
147,0.026943,0.000619,0.012146,4.106663e-04,1000.0,1.000,auto,rbf,"{'C': 1000, 'epsilon': 1, 'gamma': 'auto', 'ke...",0.732233,0.717371,0.687693,0.708649,0.612047,0.691598,0.042308,11
148,0.028528,0.005299,0.002996,3.390577e-06,1000.0,1.000,auto,poly,"{'C': 1000, 'epsilon': 1, 'gamma': 'auto', 'ke...",0.802116,0.788335,0.823366,0.809353,0.724028,0.789440,0.034607,5
149,0.026336,0.001203,0.002784,3.947217e-04,1000.0,1.000,auto,linear,"{'C': 1000, 'epsilon': 1, 'gamma': 'auto', 'ke...",0.686122,0.598327,0.585690,0.573965,0.555772,0.599975,0.045296,23

In [17]:
age_input=float(input("Age=:"))
bmi_input=float(input("BMI=:"))
children_input=float(input("Children=:"))
sex_male_input=int(input("Sex=:"))
smoker_yes_input=int(input("Smoker=:"))

Age=: 32
BMI=: 24
Children=: 2
Sex=: 1
Smoker=: 0

In [18]:
future_prediction = grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future Prediction ={}".format(future_prediction))

Future Prediction =[12231225.44970761]