In [1]:
import pandas as pd
dataset = pd.read_csv("insurance_pre.csv")

In [2]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset = pd.get_dummies(dataset, drop_first = True).astype(int)

In [4]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
independent = dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [7]:
dependent = dataset[['charges']]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

param_grid = {'criterion': ['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],
       'bootstrap': [True, False]}

grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose = 3, n_jobs=1)
grid.fit(independent, dependent)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 1/5] END bootstrap=True, criterion=squared_error;, score=0.842 total time=   0.3s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END bootstrap=True, criterion=squared_error;, score=0.763 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END bootstrap=True, criterion=squared_error;, score=0.855 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 4/5] END bootstrap=True, criterion=squared_error;, score=0.809 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END bootstrap=True, criterion=squared_error;, score=0.835 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 1/5] END bootstrap=True, criterion=absolute_error;, score=0.834 total time=   1.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END bootstrap=True, criterion=absolute_error;, score=0.770 total time=   1.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END bootstrap=True, criterion=absolute_error;, score=0.850 total time=   1.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 4/5] END bootstrap=True, criterion=absolute_error;, score=0.819 total time=   1.1s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END bootstrap=True, criterion=absolute_error;, score=0.838 total time=   1.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 1/5] END bootstrap=True, criterion=friedman_mse;, score=0.840 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END bootstrap=True, criterion=friedman_mse;, score=0.763 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END bootstrap=True, criterion=friedman_mse;, score=0.857 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 4/5] END bootstrap=True, criterion=friedman_mse;, score=0.802 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END bootstrap=True, criterion=friedman_mse;, score=0.830 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 1/5] END .bootstrap=True, criterion=poisson;, score=0.838 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END .bootstrap=True, criterion=poisson;, score=0.765 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END .bootstrap=True, criterion=poisson;, score=0.856 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 4/5] END .bootstrap=True, criterion=poisson;, score=0.804 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END .bootstrap=True, criterion=poisson;, score=0.831 total time=   0.3s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 1/5] END bootstrap=False, criterion=squared_error;, score=0.764 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END bootstrap=False, criterion=squared_error;, score=0.675 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END bootstrap=False, criterion=squared_error;, score=0.759 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 4/5] END bootstrap=False, criterion=squared_error;, score=0.713 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END bootstrap=False, criterion=squared_error;, score=0.687 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 1/5] END bootstrap=False, criterion=absolute_error;, score=0.721 total time=   1.8s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END bootstrap=False, criterion=absolute_error;, score=0.683 total time=   1.9s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END bootstrap=False, criterion=absolute_error;, score=0.760 total time=   1.8s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 4/5] END bootstrap=False, criterion=absolute_error;, score=0.738 total time=   1.9s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END bootstrap=False, criterion=absolute_error;, score=0.736 total time=   1.8s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 1/5] END bootstrap=False, criterion=friedman_mse;, score=0.761 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END bootstrap=False, criterion=friedman_mse;, score=0.672 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END bootstrap=False, criterion=friedman_mse;, score=0.759 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 4/5] END bootstrap=False, criterion=friedman_mse;, score=0.713 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END bootstrap=False, criterion=friedman_mse;, score=0.688 total time=   0.2s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 1/5] END bootstrap=False, criterion=poisson;, score=0.754 total time=   0.3s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 2/5] END bootstrap=False, criterion=poisson;, score=0.656 total time=   0.3s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 3/5] END bootstrap=False, criterion=poisson;, score=0.733 total time=   0.3s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 4/5] END bootstrap=False, criterion=poisson;, score=0.705 total time=   0.3s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

[CV 5/5] END bootstrap=False, criterion=poisson;, score=0.725 total time=   0.3s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=1,
             param_grid={'bootstrap': [True, False],
                         'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson']},
             verbose=3)

In [10]:
print("The R score value for the best parameter {}".format(grid.best_params_))

The R score value for the best parameter {'bootstrap': True, 'criterion': 'absolute_error'}

In [11]:
re = grid.cv_results_

In [12]:
table = pd.DataFrame.from_dict(re)

In [13]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_bootstrap,param_criterion,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.315962,0.030896,0.014491,7.805133e-03,True,squared_error,"{'bootstrap': True, 'criterion': 'squared_error'}",0.842158,0.763151,0.855207,0.808893,0.834915,0.820865,0.032571,2
1,1.126418,0.020955,0.017355,3.463698e-03,True,absolute_error,"{'bootstrap': True, 'criterion': 'absolute_err...",0.834055,0.770354,0.850088,0.818557,0.837888,0.822189,0.027805,1
2,0.284570,0.004423,0.011670,5.109025e-03,True,friedman_mse,"{'bootstrap': True, 'criterion': 'friedman_mse'}",0.840097,0.763227,0.857204,0.801502,0.829764,0.818359,0.032970,4
3,0.329889,0.012312,0.009375,7.654461e-03,True,poisson,"{'bootstrap': True, 'criterion': 'poisson'}",0.837720,0.764750,0.855564,0.804354,0.831028,0.818683,0.031588,3
4,0.327278,0.007874,0.012507,6.253423e-03,False,squared_error,"{'bootstrap': False, 'criterion': 'squared_err...",0.763613,0.674844,0.759457,0.713389,0.686923,0.719645,0.036429,6
5,1.922205,0.011608,0.015201,8.435489e-04,False,absolute_error,"{'bootstrap': False, 'criterion': 'absolute_er...",0.721405,0.682883,0.760242,0.738013,0.735852,0.727679,0.025612,5
6,0.308990,0.004567,0.015622,7.599534e-07,False,friedman_mse,"{'bootstrap': False, 'criterion': 'friedman_mse'}",0.760980,0.672448,0.758606,0.712670,0.688002,0.718541,0.036050,7
7,0.383963,0.008046,0.012498,6.248927e-03,False,poisson,"{'bootstrap': False, 'criterion': 'poisson'}",0.754296,0.656132,0.733423,0.705008,0.724577,0.714687,0.033287,8

In [14]:
age_input=float(input("Age=:"))
bmi_input=float(input("BMI=:"))
children_input=float(input("Children=:"))
sex_male_input=int(input("Sex=:"))
smoker_yes_input=int(input("Smoker=:"))

Age=: 33
BMI=: 24
Children=: 2
Sex=: 1
Smoker=: 0

In [15]:
future_prediction = grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future Prediction ={}".format(future_prediction))

Future Prediction =[7677.54]

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(