In [1]:
import pandas as pd
dataset = pd.read_csv("insurance_pre.csv")

In [2]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset = pd.get_dummies(dataset, drop_first = True).astype(int)

In [4]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
independent = dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [7]:
dependent = dataset[['charges']]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR

param_grid = {'kernel': ['rbf', 'poly', 'linear'], 'gamma': ['scale']}

grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3, n_jobs=1)
grid.fit(independent, dependent)

Fitting 5 folds for each of 3 candidates, totalling 15 fits
[CV 1/5] END ..........gamma=scale, kernel=rbf;, score=-0.115 total time=   0.0s
[CV 2/5] END ..........gamma=scale, kernel=rbf;, score=-0.110 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 3/5] END ..........gamma=scale, kernel=rbf;, score=-0.080 total time=   0.0s
[CV 4/5] END ..........gamma=scale, kernel=rbf;, score=-0.104 total time=   0.0s
[CV 5/5] END ..........gamma=scale, kernel=rbf;, score=-0.108 total time=   0.0s
[CV 1/5] END .........gamma=scale, kernel=poly;, score=-0.094 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[CV 2/5] END .........gamma=scale, kernel=poly;, score=-0.073 total time=   0.0s
[CV 3/5] END .........gamma=scale, kernel=poly;, score=-0.065 total time=   0.0s
[CV 4/5] END .........gamma=scale, kernel=poly;, score=-0.092 total time=   0.0s
[CV 5/5] END .........gamma=scale, kernel=poly;, score=-0.113 total time=   0.0s
[CV 1/5] END .......gamma=scale, kernel=linear;, score=-0.148 total time=   0.0s
[CV 2/5] END .......gamma=scale, kernel=linear;, score=-0.091 total time=   0.0s
[CV 3/5] END .......gamma=scale, kernel=linear;, score=-0.105 total time=   0.0s
[CV 4/5] END .......gamma=scale, kernel=linear;, score=-0.124 total time=   0.0s
[CV 5/5] END .......gamma=scale, kernel=linear;, score=-0.202 total time=   0.0s

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=1,
             param_grid={'gamma': ['scale'],
                         'kernel': ['rbf', 'poly', 'linear']},
             verbose=3)

In [9]:
print("The R score value for the best parameter {}".format(grid.best_params_))

The R score value for the best parameter {'gamma': 'scale', 'kernel': 'poly'}

In [10]:
re = grid.cv_results_

In [11]:
table = pd.DataFrame.from_dict(re)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.051896,0.008685,0.026907,0.004829,scale,rbf,"{'gamma': 'scale', 'kernel': 'rbf'}",-0.115378,-0.110221,-0.079861,-0.104073,-0.108368,-0.103580,0.012402,2
1,0.039239,0.006793,0.000994,0.001989,scale,poly,"{'gamma': 'scale', 'kernel': 'poly'}",-0.094133,-0.073192,-0.064713,-0.092259,-0.113371,-0.087534,0.017088,1
2,0.034306,0.008462,0.015035,0.005843,scale,linear,"{'gamma': 'scale', 'kernel': 'linear'}",-0.147686,-0.090673,-0.104913,-0.123857,-0.202412,-0.133908,0.039227,3

In [13]:
age_input=float(input("Age=:"))
bmi_input=float(input("BMI=:"))
children_input=float(input("Children=:"))
sex_male_input=int(input("Sex=:"))
smoker_yes_input=int(input("Smoker=:"))

Age=: 33
BMI=: 24
Children=: 2
Sex=: 1
Smoker=: 0

In [14]:
future_prediction = grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future Prediction ={}".format(future_prediction))

Future Prediction =[7588.30849319]

C:\Users\Balasaravanamuthu\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(